name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
      strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 2 copies of the current job in parallel
        containers: [1, 2]
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2

     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome